# Generated by Django 4.2 on 2025-04-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Eğitim Senaryosu İsmi')),
                ('description', models.TextField(verbose_name='Eğitim Senaryosu Açıklaması')),
                ('scenario_document', models.FileField(upload_to='documents/scenario_documents/', verbose_name='Eğitim Senaryosu Dokümanı')),
                ('review_document', models.FileField(upload_to='documents/review_documents/', verbose_name='Eğitim Senaryosu Değerlendirme Dokümanı')),
                ('ai_level', models.CharField(choices=[('personel', 'Çalışan'), ('manager', 'Yönetici'), ('highLevel', 'Üst Düzey Yönetici')], max_length=100, verbose_name='AI Seviyesi')),
                ('user_level', models.CharField(choices=[('personel', 'Çalışan'), ('manager', 'Yönetici'), ('highLevel', 'Üst Düzey Yönetici')], max_length=100, verbose_name='Kullanıcı Seviyesi')),
                ('hardness', models.CharField(choices=[('veryEasy', 'Çok Kolay'), ('easy', 'Kolay'), ('medium', 'Orta'), ('hard', 'Zor'), ('veryHard', 'Çok Zor')], max_length=100, verbose_name='Zorluk Seviyesi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='UserEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('entry_name', models.CharField(default='New Entry', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.CreateModel(
            name='UserChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('gpt_response', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='my_app.userentry')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
