# Generated by Django 5.2 on 2026-02-20 17:32

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Otomatik olarak e-posta ile aynı değere set edilir.', max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('phone_number', models.CharField(blank=True, help_text='İsteğe bağlı, Google veya klasik kayıtta tutulabilir.', max_length=20, null=True, verbose_name='Telefon')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_kodu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosya Kodu')),
                ('dosya_adi', models.CharField(max_length=200, verbose_name='Dosya Adı')),
                ('dosya_turu', models.CharField(default='DAVA', max_length=50, verbose_name='Dosya Türü')),
                ('yargi_mercii', models.CharField(max_length=200, verbose_name='Yargı Mercii / Birim')),
                ('esas_no', models.CharField(max_length=100, verbose_name='Esas No')),
                ('karar_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Karar No')),
                ('konu_ozeti', models.TextField(blank=True, null=True, verbose_name='Konu Özeti')),
                ('durum', models.CharField(choices=[('ACIK', 'Açık'), ('KAPALI', 'Kapalı'), ('ASKIDA', 'Askıda')], default='ACIK', max_length=10, verbose_name='Durum')),
                ('acilis_tarihi', models.DateField(verbose_name='Açılış Tarihi')),
                ('kapanis_tarihi', models.DateField(blank=True, null=True, verbose_name='Kapanış Tarihi')),
                ('muvekkil_ad_unvan', models.CharField(max_length=200, verbose_name='Müvekkil Ad/Unvan')),
                ('karsi_taraf_ad_unvan', models.CharField(max_length=200, verbose_name='Karşı Taraf Ad/Unvan')),
                ('para_birimi', models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('devreden_bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Devreden Bakiye')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('decisions', 'Kararlar'), ('user_docs', 'Kullanıcı Dokümanları'), ('hybrid', 'Hibrit')], default='decisions', max_length=20, verbose_name='Sohbet Modu')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('filters', models.JSONField(blank=True, help_text='Arama filtreleri (daire, tarih vb.)', null=True, verbose_name='Filtreler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, help_text='Opsiyonel: Sohbet belirli bir dava dosyasıyla ilişkilendirilebilir', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='my_app.casefile', verbose_name='İlişkili Dava')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(verbose_name='Kullanıcı Sorgusu')),
                ('ai_response', models.TextField(blank=True, null=True, verbose_name='AI Yanıtı')),
                ('sources', models.JSONField(blank=True, help_text='RAG tarafından kullanılan kaynak chunk bilgileri', null=True, verbose_name='Kaynaklar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='my_app.chatsession', verbose_name='Oturum')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('file_url', models.CharField(help_text='Cloud storage path', max_length=500, verbose_name='Dosya Yolu (R2)')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10, verbose_name='Dosya Türü')),
                ('text_extracted', models.BooleanField(default=False, verbose_name='Metin Çıkarıldı mı?')),
                ('indexed', models.BooleanField(default=False, verbose_name='Vektör Indexlendi mi?')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='my_app.casefile', verbose_name='Dava Dosyası')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_tarihi', models.DateField(verbose_name='İşlem Tarihi')),
                ('islem_tipi', models.CharField(choices=[('MASRAF', 'Masraf'), ('AVANS_ALINDI', 'Avans Alındı'), ('AVANS_IADE', 'Avans İade')], max_length=20, verbose_name='İşlem Tipi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('receipt_type', models.CharField(blank=True, choices=[('BELGELI', 'Belgeli'), ('BELGESIZ', 'Belgesiz')], max_length=10, null=True, verbose_name='Belge Tipi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tutar')),
                ('para_birimi', models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('odeme_yapan', models.CharField(blank=True, choices=[('OFIS', 'Ofis'), ('MUVEKKIL', 'Müvekkil')], max_length=10, null=True, verbose_name='Ödeyen')),
                ('muvekkile_yansit', models.BooleanField(default=False, verbose_name='Müvekkile Yansıt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='my_app.casefile', verbose_name='Dava Dosyası')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.expensecategory', verbose_name='Kategori')),
            ],
            options={
                'ordering': ['-islem_tarihi', '-created_at'],
            },
        ),
    ]
