# Generated by Django 4.2 on 2025-04-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='review_document',
            field=models.FileField(upload_to='documents/', verbose_name='Eğitim Senaryosu Değerlendirme Dokümanı'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_document',
            field=models.FileField(upload_to='documents/', verbose_name='Eğitim Senaryosu Dokümanı'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='entry_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.scenario', verbose_name='Eğitim Senaryosu'),
        ),
    ]
