# Generated by Django 5.2 on 2026-02-20 17:37

import my_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', my_app.models.UserManager()),
            ],
        ),
    ]
