# Generated by Django 4.2 on 2025-04-10 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_scenario_review_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userentry',
            old_name='entry_name',
            new_name='scenario',
        ),
    ]
