# Generated by Django 4.2 on 2025-04-14 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_entry_name_userentry_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='ai_level',
            field=models.CharField(choices=[('employee', 'Çalışan'), ('manager', 'Yönetici'), ('highLevel', 'Üst Düzey Yönetici')], max_length=100, verbose_name='AI Seviyesi'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(help_text='Eğitim senaryosu hakkında kısa bir açıklama yazın.', verbose_name='Eğitim Senaryosu Açıklaması'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='review_document',
            field=models.FileField(help_text='PDF veya DOCX formatında olmalıdır.', upload_to='documents/', verbose_name='Eğitim Senaryosu Değerlendirme Dokümanı'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='scenario_document',
            field=models.FileField(help_text='PDF veya DOCX formatında olmalıdır.', upload_to='documents/', verbose_name='Eğitim Senaryosu Dokümanı'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='user_level',
            field=models.CharField(choices=[('employee', 'Çalışan'), ('manager', 'Yönetici'), ('highLevel', 'Üst Düzey Yönetici')], max_length=100, verbose_name='Kullanıcı Seviyesi'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='my_app.scenario', verbose_name='Eğitim Senaryosu'),
        ),
    ]
