# Generated by Django 4.2 on 2025-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_scenario_ai_level_alter_scenario_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='ai_level',
            field=models.CharField(choices=[('employee', 'Çalışan'), ('manager', 'Yönetici'), ('highLevel', 'Üst Düzey Yönetici'), ('customer', 'Müşteri')], max_length=100, verbose_name='AI Seviyesi'),
        ),
    ]
