# Generated by Django 4.2 on 2025-05-09 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0005_alter_scenario_ai_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Müşteri İsmi')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-posta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('logo', models.ImageField(blank=True, help_text='Müşteri logosu yükleyin. (PNG, JPG formatında)', null=True, upload_to='logos/', verbose_name='Logo')),
                ('users', models.ManyToManyField(blank=True, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcılar')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İlerleme Yüzdesi')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Program İsmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Grup İsmi')),
                ('group_date', models.DateField(blank=True, null=True, verbose_name='Eğitim Tarihi')),
                ('progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='İlerleme Yüzdesi (Ortalama)')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.customer', verbose_name='Müşteri')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.program', verbose_name='Program')),
                ('users', models.ManyToManyField(related_name='training_groups', through='my_app.GroupUser', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcılar')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_percentage', models.DecimalField(decimal_places=2, help_text='Senaryonun program içindeki ağırlığını belirtin. (0-100)', max_digits=5, verbose_name='Ağırlık Yüzdesi')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.program', verbose_name='Program')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.scenario', verbose_name='Eğitim Senaryosu')),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='scenarios',
            field=models.ManyToManyField(through='my_app.ProgramScenario', to='my_app.scenario', verbose_name='Eğitim Senaryoları'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='training_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.traininggroup', verbose_name='Grup'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
