# Generated by Django 4.2 on 2025-05-11 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0006_customer_groupuser_program_traininggroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupuser',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Katılımcı'),
        ),
        migrations.AlterField(
            model_name='programscenario',
            name='scenario',
            field=models.ForeignKey(help_text='Programa eklenecek eğitim senaryolarını seçin.', on_delete=django.db.models.deletion.CASCADE, to='my_app.scenario', verbose_name='Eğitim Senaryosu'),
        ),
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('training_group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='programscenario',
            unique_together={('program', 'scenario')},
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(verbose_name='Değerlendirme Raporu')),
                ('score', models.IntegerField(verbose_name='Değerlendirme Puanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.customer', verbose_name='Müşteri')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.scenario', verbose_name='Eğitim Senaryosu')),
                ('training_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.traininggroup', verbose_name='Grup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
