# Generated by Django 4.2 on 2025-05-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_groupuser_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
    ]
