# Generated by Django 4.2 on 2025-05-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='programscenario',
            name='release_date',
            field=models.DateField(blank=True, help_text='Senaryonun yayınlanacağı tarih', null=True, verbose_name='Yayın Tarihi'),
        ),
    ]
