# Generated by Django 4.2 on 2025-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_programscenario_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupuser',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ortalama Değerlendirme Puanı'),
        ),
    ]
