# Generated by Django 4.2 on 2025-05-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_groupuser_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='training_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.traininggroup', verbose_name='Grup'),
        ),
    ]
