# Generated by Django 4.2 on 2025-06-02 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_userentry_training_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='training_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.traininggroup', verbose_name='Grup'),
        ),
    ]
