# Generated by Django 4.2 on 2025-06-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_userentry_training_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='type',
            field=models.CharField(blank=True, choices=[('pre', 'Ön'), ('post', 'Son')], max_length=10, null=True, verbose_name='Değerlendirme Türü'),
        ),
        migrations.AddField(
            model_name='programscenario',
            name='close_date',
            field=models.DateField(blank=True, help_text='Senaryonun kapanış tarihi', null=True, verbose_name='Kapanış Tarihi'),
        ),
        migrations.AddField(
            model_name='programscenario',
            name='training_date',
            field=models.DateField(blank=True, help_text='Senaryonun eğitim tarihi', null=True, verbose_name='Eğitim Tarihi'),
        ),
    ]
