# Generated by Django 4.2 on 2025-06-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_evaluationreport_type_programscenario_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='bg_image',
            field=models.ImageField(blank=True, help_text='Eğitim senaryosu için arka plan resmi yükleyin. (PNG, JPG formatında)', null=True, upload_to='backgrounds/', verbose_name='Arka Plan Resmi'),
        ),
    ]
