# Generated by Django 4.2 on 2025-06-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_scenario_bg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='voice',
            field=models.CharField(choices=[('alloy', 'Alloy'), ('ash', 'Ash'), ('ballad', 'Ballad'), ('coral', 'Coral'), ('echo', 'Echo'), ('fable', 'Fable'), ('nova', 'Nova'), ('onyx', 'Onyx'), ('sage', 'Sage'), ('shimmer', 'Shimmer')], default='nova', help_text='Bu senaryo için kullanılacak TTS sesi (OpenAI destekli)', max_length=20, verbose_name='TTS Ses Profili'),
        ),
    ]
