# Generated by Django 4.2 on 2025-07-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_scenario_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Kilitli mi'),
        ),
    ]
