# Generated by Django 4.2 on 2025-07-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_userentry_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1, help_text='Bu raporun kaçıncı deneme olduğunu gösterir.', verbose_name='Deneme Sayısı'),
        ),
        migrations.AddField(
            model_name='programscenario',
            name='max_attempts',
            field=models.PositiveIntegerField(default=50, help_text='Senaryonun maksimum deneme sayısını belirtin.', verbose_name='Maksimum Deneme Sayısı'),
        ),
    ]
