# Generated by Django 4.2 on 2025-08-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_evaluationreport_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupuser',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Katılımcının Eğitim Programındaki Senaryolardan Aldığı Ağırlıklı Ortalama Puanı', max_digits=5, null=True, verbose_name='Ortalama Değerlendirme Puanı'),
        ),
    ]
