# Generated by Django 4.2 on 2025-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_alter_groupuser_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programscenario',
            name='max_attempts',
            field=models.PositiveIntegerField(default=200, help_text='Senaryonun maksimum deneme sayısını belirtin.', verbose_name='Maksimum Deneme Sayısı'),
        ),
    ]
