# Generated by Django 4.2 on 2025-12-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_programscenario_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='initial_message',
            field=models.TextField(blank=True, help_text='Simülasyon açılışında kullanıcının göndereceği ilk mesaj.', null=True, verbose_name='İlk Kullanıcı Mesajı'),
        ),
    ]
