# Generated by Django 4.2 on 2025-12-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_scenario_initial_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='initial_message',
            field=models.TextField(blank=True, help_text='Simülasyon açılışında kullanıcının göndereceği ilk mesaj. Boş bırakılırsa varsayılan mesaj kullanılır.', null=True, verbose_name='İlk Kullanıcı Mesajı'),
        ),
    ]
