# Generated by Django 4.2 on 2025-12-16 22:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0023_alter_scenario_initial_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininggroup',
            name='trainers',
            field=models.ManyToManyField(blank=True, help_text='Bu eğitim grubunun eğitmen(ler)ini seçin.', related_name='trainer_groups', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmenler'),
        ),
    ]
