# Generated by Django 4.2 on 2026-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_traininggroup_trainers'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationreport',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kullanıcının bu senaryo için tüm denemelerinin ortalaması', max_digits=5, null=True, verbose_name='Ortalama Puan'),
        ),
    ]
