# Generated by Django 4.2 on 2026-01-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_evaluationreport_average_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mixed_group',
            field=models.BooleanField(default=False, help_text='Farklı müşterilere kayıtlı kullanıcıları atamak için bu seçeneği etkinleştirin.', verbose_name='Karma Grup'),
        ),
    ]
